name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pipx
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipx
          python -m pipx ensurepath
        shell: bash

      - name: Install Poetry with pipx
        run: |
          pipx install poetry
        shell: bash

      - name: Install project dependencies
        run: |
          make install
        shell: bash

      # Run Makefile commands for linting and type-checking
      - name: Lint and type-checking
        run: |
          make check
        shell: bash

